import { socialCallName } from './call';

export enum DataHubSubscriptionEventEnum {
  POST_CREATED = 'POST_CREATED',
  POST_STATE_UPDATED = 'POST_STATE_UPDATED',

  POST_FOLLOWED = 'POST_FOLLOWED',
  POST_FOLLOW_STATE_UPDATED = 'POST_FOLLOW_STATE_UPDATED',

  EVM_ADDRESS_LINKED_TO_ACCOUNT = 'EVM_ADDRESS_LINKED_TO_ACCOUNT',
  EVM_ADDRESS_LINK_TO_ACCOUNT_STATE_UPDATED = 'EVM_ADDRESS_LINK_TO_ACCOUNT_STATE_UPDATED',

  LINKED_IDENTITY_CREATED = 'LINKED_IDENTITY_CREATED',
  LINKED_IDENTITY_STATE_UPDATED = 'LINKED_IDENTITY_STATE_UPDATED',
  LINKED_IDENTITY_SESSION_CREATED = 'LINKED_IDENTITY_SESSION_CREATED',
  LINKED_IDENTITY_SESSION_STATE_UPDATED = 'LINKED_IDENTITY_SESSION_STATE_UPDATED',
  LINKED_IDENTITY_EXTERNAL_PROVIDER_CREATED = 'LINKED_IDENTITY_EXTERNAL_PROVIDER_CREATED',
  LINKED_IDENTITY_EXTERNAL_PROVIDER_STATE_UPDATED = 'LINKED_IDENTITY_EXTERNAL_PROVIDER_STATE_UPDATED',

  MODERATION_MODERATOR_CREATED = 'MODERATION_MODERATOR_CREATED',
  MODERATION_MODERATOR_STATE_UPDATED = 'MODERATION_MODERATOR_STATE_UPDATED',

  MODERATION_BLOCKED_RESOURCE_CREATED = 'MODERATION_BLOCKED_RESOURCE_CREATED',
  MODERATION_BLOCKED_RESOURCE_STATE_UPDATED = 'MODERATION_BLOCKED_RESOURCE_STATE_UPDATED',

  MODERATION_ORGANIZATION_CREATED = 'MODERATION_ORGANIZATION_CREATED',
  MODERATION_ORGANIZATION_STATE_UPDATED = 'MODERATION_ORGANIZATION_STATE_UPDATED',

  ACTIVE_STAKING_SUPER_LIKE_CREATED = 'ACTIVE_STAKING_SUPER_LIKE_CREATED',
  ACTIVE_STAKING_SUPER_LIKE_STATE_UPDATED = 'ACTIVE_STAKING_SUPER_LIKE_STATE_UPDATED',

  SOCIAL_PROFILE_BALANCES_CREATED = 'SOCIAL_PROFILE_BALANCES_CREATED',
  SOCIAL_PROFILE_BALANCES_STATE_UPDATED = 'SOCIAL_PROFILE_BALANCES_STATE_UPDATED',

  SERVICE_ACCOUNT_INFO_EVENT = 'SERVICE_ACCOUNT_INFO_EVENT',
  SERVICE_ACCOUNT_SUCCESS_EVENT = 'SERVICE_ACCOUNT_SUCCESS_EVENT',
  SERVICE_ACCOUNT_ERROR_EVENT = 'SERVICE_ACCOUNT_ERROR_EVENT',
  SERVICE_ACCOUNT_WARNING_EVENT = 'SERVICE_ACCOUNT_WARNING_EVENT'
}

export enum ServiceMessageStatusCode {
  INFO = 'INFO',
  PROCESSED = 'PROCESSED',
  CREATED = 'CREATED',
  UPDATED = 'UPDATED',
  MOVED = 'MOVED',

  WARNING = 'WARNING',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  ENTITY_ALREADY_EXISTS = 'ENTITY_ALREADY_EXISTS',
  ENTITY_NOT_FOUND = 'ENTITY_NOT_FOUND',
  TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  UNPROCESSABLE_ENTITY = 'UNPROCESSABLE_ENTITY',
  PAYMENT_REQUIRED = 'PAYMENT_REQUIRED',
  INSUFFICIENT_BALANCE = 'INSUFFICIENT_BALANCE',
  BAD_REQUEST = 'BAD_REQUEST',
  INVALID_SIGNER = 'INVALID_SIGNER',
  INVALID_PROXY_FOR_SIGNER = 'INVALID_PROXY_FOR_SIGNER',
  DAILY_TAPS_MAX_LIMIT_REACHED = 'DAILY_TAPS_MAX_LIMIT_REACHED',
  INVALID_TAPS_VALUE = 'INVALID_TAPS_VALUE',
  DAILY_SUPER_LIKES_MAX_LIMIT_REACHED = 'DAILY_SUPER_LIKES_MAX_LIMIT_REACHED'
}

export type SubscriptionServiceMessageMeta = {
  code: ServiceMessageStatusCode;
  msg?: string;
  extension?: Record<any, any>;
};

export type SubscriptionServiceMessageToTargetMeta = {
  targetAddress: string;
  code: ServiceMessageStatusCode;
  callId?: string;
  callName?: keyof typeof socialCallName;
  msg?: string;
  extension?: Record<any, any>;
};

export type SubscriptionServiceMessage = {
  event: DataHubSubscriptionEventEnum;
  meta: SubscriptionServiceMessageMeta;
};

export type SubscriptionServiceMessageToTarget = {
  event: DataHubSubscriptionEventEnum;
  meta: SubscriptionServiceMessageToTargetMeta;
};

export type SubscriptionServiceAccountToken = {
  sig: string;
  msg: {
    address?: string;
    proxy?: string;
    signer?: string;
    timestamp: string;
  };
};
