export enum DataHubSubscriptionEventEnum {
  POST_CREATED = 'POST_CREATED',
  POST_STATE_UPDATED = 'POST_STATE_UPDATED',

  POST_FOLLOWED = 'POST_FOLLOWED',
  POST_FOLLOW_STATE_UPDATED = 'POST_FOLLOW_STATE_UPDATED',

  EVM_ADDRESS_LINKED_TO_ACCOUNT = 'EVM_ADDRESS_LINKED_TO_ACCOUNT',
  EVM_ADDRESS_LINK_TO_ACCOUNT_STATE_UPDATED = 'EVM_ADDRESS_LINK_TO_ACCOUNT_STATE_UPDATED',

  TWITTER_IDENTITY_CREATED = 'TWITTER_IDENTITY_CREATED',
  TWITTER_IDENTITY_STATE_UPDATED = 'TWITTER_IDENTITY_STATE_UPDATED'
}
