export enum DataHubSubscriptionEventEnum {
  POST_CREATED = 'POST_CREATED',
  POST_STATE_UPDATED = 'POST_STATE_UPDATED',

  POST_FOLLOWED = 'POST_FOLLOWED',
  POST_FOLLOW_STATE_UPDATED = 'POST_FOLLOW_STATE_UPDATED',

  EVM_ADDRESS_LINKED_TO_ACCOUNT = 'EVM_ADDRESS_LINKED_TO_ACCOUNT',
  EVM_ADDRESS_LINK_TO_ACCOUNT_STATE_UPDATED = 'EVM_ADDRESS_LINK_TO_ACCOUNT_STATE_UPDATED',

  LINKED_IDENTITY_CREATED = 'LINKED_IDENTITY_CREATED',
  LINKED_IDENTITY_STATE_UPDATED = 'LINKED_IDENTITY_STATE_UPDATED',

  MODERATION_MODERATOR_CREATED = 'MODERATION_MODERATOR_CREATED',
  MODERATION_MODERATOR_STATE_UPDATED = 'MODERATION_MODERATOR_STATE_UPDATED',

  MODERATION_BLOCKED_RESOURCE_CREATED = 'MODERATION_BLOCKED_RESOURCE_CREATED',
  MODERATION_BLOCKED_RESOURCE_STATE_UPDATED = 'MODERATION_BLOCKED_RESOURCE_STATE_UPDATED'
}
